### ISSUE TITLE
Teşekkürler

### ISSUE THREAD

**Issue by telase** [Umut-D/IptvEditor#1]
valla yaptığın programlara baktım sitende,helal olsun sana arkadaşım,başarılar dilerim.

Bu arada iptv editörünü alıp biraz değiştirerek kullanıp sunacağım :)
Yarın öbürgün benim adımla editörünü görürsen kızma bana.
selamlar

**Comment by Umut-D** [comment]
Güzel sözler için teşekkürler :)

Değiştir, kullan, sun. Ama bir yerde "Umut D.'nin IPTV Editör programı temel alınarak geliştirilmiştir" yazarsan çok sevinirim.

**Comment by telase** [comment]
valla gece arkadaşımın forumu için düzenleme yapıp sundum.
"Umut D.'nin IPTV Editör programı temel alınarak geliştirilmiştir"  yazamadım,özür dilerim.
ama kendi forumum için yaptığımda  adını yazacağım.

**Comment by telase** [comment]
ve kendi forumum içinde düzenleme yapıp sundum.
http://telase.site/showthread.php?tid=289


tekrar teşekkür ederim,başarılar dilerim

**Comment by Umut-D** [comment]
İlgin ve emeğe saygın için ben teşekkür ederim telase 👍🏻
